services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: umumswp
    container_name: umumswp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    ports:
      - "8004:8080"
    networks:
      - alzaid-net

networks:
  alzaid-net:
    external: true
