services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: umumswp
    container_name: umumswp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./src/vendor:/var/www/vendor
      - ./src/node_modules:/var/www/node_modules

    ports:
      - "8003:8080"

    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: db_setwapres
      DB_USERNAME: "alzaid777"
      DB_PASSWORD: "setwapres"

    networks:
      - shared-net

networks:
  shared-net:
    external: true
