services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: umumswp
    container_name: umumswp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    ports:
      - "8003:8080"
